In [1]:
import pandas as pd
import altair as alt
import warnings
warnings.filterwarnings("ignore", category=FutureWarning) # Turn off distracting warnings

# Part 1 - Data Cleaning

## Data Loading
We load the data, provided in `hw2-crowd-data.csv`

In [2]:
df_cars =pd.read_csv("hw2-crowd-data.csv")
df_cars.head()

,Car Make,Car Model,Dealer or Individual?,Price,Year,Location,Mileage,Doors,Color,VIN#,Engine,Description,Web Link
0,Honda,Accord,Dealer,"23,890",2022,"Atlanta, GA",31,4,Black,1HGCV1F45NA026725,192 hp 1.5L I4,Hennessy Lexus of Atlanta is proud to offer yo...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
1,Honda,Accord,Dealer,"23,749",2022,"Atlanta, GA","75,633",4,White,1HGCV1F46NA008329,192 hp 1.5L I4,#1 PRICE & #1 VALUE IN THE ATLANTA AREA!! Hond...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
2,Honda,Accord,Dealer,"23,465",2022,"Marietta, GA","63,411",4,Dark Blue,1HGCV1F37NA005057,192 hp 1.5L I4,At MEGA Motors your trusted used car dealershi...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
3,Honda,Accord,Dealer,"15,998",NaN,NaN,"133,241",4,White,1HGCV1F41JA064964,192 hp 1.5L I4,At MEGA Motors your trusted used car dealershi...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
4,Honda,Accord,Dealer,"$5,800",2008,"Flint, MI","124,145",4,gray,1HGCP36898A044545,6 Cyl,"Last serviced at 122,605 miles in Livonia, MI ...",https://www.carfax.com/vehicle/1HGCP36898A044545

In [3]:
# what is the length of my dataframe?
len(df_cars)

437

In [4]:
print("Column names:", df_cars.columns.tolist())
print("Number of rows and columns:", df_cars.shape)
df_cars.info()

Column names: ['Car Make', 'Car Model', 'Dealer or Individual?', 'Price', 'Year', 'Location', 'Mileage', 'Doors', 'Color', 'VIN#', 'Engine', 'Description', 'Web Link']
Number of rows and columns: (437, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 437 entries, 0 to 436
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Car Make               437 non-null    object
 1   Car Model              437 non-null    object
 2   Dealer or Individual?  437 non-null    object
 3   Price                  437 non-null    object
 4   Year                   389 non-null    object
 5   Location               287 non-null    object
 6   Mileage                436 non-null    object
 7   Doors                  437 non-null    object
 8   Color                  435 non-null    object
 9   VIN#                   435 non-null    object
 10  Engine                 437 non-null    object
 11  Description            413 non-null    object
 12  Web Link               437 non-null    object
dtypes: object(13)
memory usage: 44.5+ KB

## Data Cleaning
You need to clean the rows and columns of data using Pandas.  Insert the code (and descriptions of the code in markdown) in this subsection.

In [5]:
# insert code here
df_cars.isnull().sum()

Car Make                   0
Car Model                  0
Dealer or Individual?      0
Price                      0
Year                      48
Location                 150
Mileage                    1
Doors                      0
Color                      2
VIN#                       2
Engine                     0
Description               24
Web Link                   0
dtype: int64

In [6]:
df_cars_no_missing = df_cars.dropna()
df_cars_no_missing.info()

<class 'pandas.core.frame.DataFrame'>
Index: 275 entries, 0 to 434
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Car Make               275 non-null    object
 1   Car Model              275 non-null    object
 2   Dealer or Individual?  275 non-null    object
 3   Price                  275 non-null    object
 4   Year                   275 non-null    object
 5   Location               275 non-null    object
 6   Mileage                275 non-null    object
 7   Doors                  275 non-null    object
 8   Color                  275 non-null    object
 9   VIN#                   275 non-null    object
 10  Engine                 275 non-null    object
 11  Description            275 non-null    object
 12  Web Link               275 non-null    object
dtypes: object(13)
memory usage: 30.1+ KB

In [7]:
df_cars.duplicated().any()

False

In [8]:
df_cars.head()

,Car Make,Car Model,Dealer or Individual?,Price,Year,Location,Mileage,Doors,Color,VIN#,Engine,Description,Web Link
0,Honda,Accord,Dealer,"23,890",2022,"Atlanta, GA",31,4,Black,1HGCV1F45NA026725,192 hp 1.5L I4,Hennessy Lexus of Atlanta is proud to offer yo...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
1,Honda,Accord,Dealer,"23,749",2022,"Atlanta, GA","75,633",4,White,1HGCV1F46NA008329,192 hp 1.5L I4,#1 PRICE & #1 VALUE IN THE ATLANTA AREA!! Hond...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
2,Honda,Accord,Dealer,"23,465",2022,"Marietta, GA","63,411",4,Dark Blue,1HGCV1F37NA005057,192 hp 1.5L I4,At MEGA Motors your trusted used car dealershi...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
3,Honda,Accord,Dealer,"15,998",NaN,NaN,"133,241",4,White,1HGCV1F41JA064964,192 hp 1.5L I4,At MEGA Motors your trusted used car dealershi...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
4,Honda,Accord,Dealer,"$5,800",2008,"Flint, MI","124,145",4,gray,1HGCP36898A044545,6 Cyl,"Last serviced at 122,605 miles in Livonia, MI ...",https://www.carfax.com/vehicle/1HGCP36898A044545

In [9]:
if 'Car Make' in df_cars.columns and 'Car Model' in df_cars.columns and 'VIN#' in df_cars.columns:
    df_cars = df_cars.drop(columns=['Car Make','Car Model','VIN#'])

In [10]:
df_cars.head()

,Dealer or Individual?,Price,Year,Location,Mileage,Doors,Color,Engine,Description,Web Link
0,Dealer,"23,890",2022,"Atlanta, GA",31,4,Black,192 hp 1.5L I4,Hennessy Lexus of Atlanta is proud to offer yo...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
1,Dealer,"23,749",2022,"Atlanta, GA","75,633",4,White,192 hp 1.5L I4,#1 PRICE & #1 VALUE IN THE ATLANTA AREA!! Hond...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
2,Dealer,"23,465",2022,"Marietta, GA","63,411",4,Dark Blue,192 hp 1.5L I4,At MEGA Motors your trusted used car dealershi...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
3,Dealer,"15,998",NaN,NaN,"133,241",4,White,192 hp 1.5L I4,At MEGA Motors your trusted used car dealershi...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
4,Dealer,"$5,800",2008,"Flint, MI","124,145",4,gray,6 Cyl,"Last serviced at 122,605 miles in Livonia, MI ...",https://www.carfax.com/vehicle/1HGCP36898A044545

In [11]:
if 'Price' in df_cars:
    df_cars['Price'] = df_cars['Price'].replace(r'[^0-9]','',regex=True)
    df_cars['Price'] = pd.to_numeric(df_cars['Price'],errors='ignore')
    df_cars['Price'] = df_cars['Price'].astype(float)

In [12]:
if 'Mileage' in df_cars:
    df_cars['Mileage'] = df_cars['Mileage'].replace(r'[^0-9]','',regex=True)
    df_cars['Mileage'] = pd.to_numeric(df_cars['Mileage'],errors='coerce')
    df_cars = df_cars.dropna(subset=['Mileage'])
    df_cars['Mileage'] = df_cars['Mileage'].astype(float)

In [13]:
if 'Doors' in df_cars:
    df_cars['Doors'] = df_cars['Doors'].replace(r'[^0-9]','',regex=True)
    df_cars['Doors'] = pd.to_numeric(df_cars['Doors'],errors='ignore')
    df_cars = df_cars.dropna(subset=['Doors']) 
    df_cars['Doors'] = df_cars['Doors'].astype(int)

In [14]:
if 'Year' in df_cars:
    df_cars['Year'] = df_cars['Year'].replace(r'[^0-9]','',regex=True)
    df_cars['Year'] = pd.to_numeric(df_cars['Year'],errors='ignore')
    df_cars = df_cars.dropna(subset=['Year']) 
    df_cars['Year'] = df_cars['Year'].astype(int)
    df_cars = df_cars[(df_cars['Year'] >= 2008) & (df_cars['Year'] <= 2025)]

In [15]:
if 'Dealer or Individual?' in df_cars:
    col = 'Dealer or Individual?'
    df_cars[col] = df_cars[col].astype(str).str.strip().str.lower()
    invalid_rows = df_cars[~df_cars[col].isin(['dealer', 'individual'])]
    print("invalid rows:", len(invalid_rows))
    display(invalid_rows)
    mapping = {'dealer': 0, 'individual': 1}
    df_cars[col] = df_cars[col].map(mapping).fillna(2).astype('Int64')

invalid rows: 4

,Dealer or Individual?,Price,Year,Location,Mileage,Doors,Color,Engine,Description,Web Link
78,"dealer, individual",27699.0,2024,NaN,11258.0,4,Radiant Red,"1.5L I-4 gasoline direct injection, DOHC, i-V...",CarShop is completely free of the usual haggli...,https://www.cars.com/vehicledetail/1193f600-e4...
201,"dealer, individual",24926.0,2022,"Cleveland, OH",39387.0,4,Lunar Silver Metallic,192 hp 1.5L I4,It is a 2022 Honda Accord Sport Special Editio...,https://www.cargurus.com/Cars/inventorylisting...
240,"dealer, individual",10695.0,2012,Atlanta,104329.0,4,White,4 Cyl,2012 HONDA ACCORD (SPECIAL EDITION) 3 OWNERS/C...,https://www.carfax.com/vehicle/1HGCP2F6XCA004296
260,"dealer, individual",12999.0,2012,NaN,52164.0,4,Black,2.4L DOHC MPFI 16-Valve i-VTEC I4 Engine,"2012 Honda Accord SE sedan, automatic transmis...",https://www.ebay.com/itm/365833779177?itmmeta=...

In [16]:
df_cars = df_cars.dropna(subset=['Mileage'])

In [17]:
df_cars.shape

(366, 10)

In [18]:
df_cars.iloc[[62]]

,Dealer or Individual?,Price,Year,Location,Mileage,Doors,Color,Engine,Description,Web Link
78,2,27699.0,2024,NaN,11258.0,4,Radiant Red,"1.5L I-4 gasoline direct injection, DOHC, i-V...",CarShop is completely free of the usual haggli...,https://www.cars.com/vehicledetail/1193f600-e4...

In [19]:
df_cars.head()
# df_cars.info()

,Dealer or Individual?,Price,Year,Location,Mileage,Doors,Color,Engine,Description,Web Link
0,0,23890.0,2022,"Atlanta, GA",31.0,4,Black,192 hp 1.5L I4,Hennessy Lexus of Atlanta is proud to offer yo...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
1,0,23749.0,2022,"Atlanta, GA",75633.0,4,White,192 hp 1.5L I4,#1 PRICE & #1 VALUE IN THE ATLANTA AREA!! Hond...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
2,0,23465.0,2022,"Marietta, GA",63411.0,4,Dark Blue,192 hp 1.5L I4,At MEGA Motors your trusted used car dealershi...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
4,0,5800.0,2008,"Flint, MI",124145.0,4,gray,6 Cyl,"Last serviced at 122,605 miles in Livonia, MI ...",https://www.carfax.com/vehicle/1HGCP36898A044545
8,0,19000.0,2017,"3269 Blinker Parkway, DuBois, PA 15801",60216.0,4,Champagne Frost Pearl,2.4L I4 16V GDI DOHC,Champagne Frost Pearl 2017 Honda Accord EX-L w...,https://www.cars.com/vehicledetail/a2020bcf-55...

In [20]:
df_cars.isnull().sum()

Dealer or Individual?     0
Price                     0
Year                      0
Location                 93
Mileage                   0
Doors                     0
Color                     2
Engine                    0
Description              12
Web Link                  0
dtype: int64

## Export Cleaned Data
Save the output of your data cleaning to `hw2-clean-data.csv`

In [21]:
df_cars.to_csv("hw2-clean-data.csv")

In [22]:
df_cars_clean =pd.read_csv("hw2-clean-data.csv")
df_cars_clean.head()

,Unnamed: 0,Dealer or Individual?,Price,Year,Location,Mileage,Doors,Color,Engine,Description,Web Link
0,0,0,23890.0,2022,"Atlanta, GA",31.0,4,Black,192 hp 1.5L I4,Hennessy Lexus of Atlanta is proud to offer yo...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
1,1,0,23749.0,2022,"Atlanta, GA",75633.0,4,White,192 hp 1.5L I4,#1 PRICE & #1 VALUE IN THE ATLANTA AREA!! Hond...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
2,2,0,23465.0,2022,"Marietta, GA",63411.0,4,Dark Blue,192 hp 1.5L I4,At MEGA Motors your trusted used car dealershi...,https://www.cargurus.com/Cars/l-Used-Honda-Acc...
3,4,0,5800.0,2008,"Flint, MI",124145.0,4,gray,6 Cyl,"Last serviced at 122,605 miles in Livonia, MI ...",https://www.carfax.com/vehicle/1HGCP36898A044545
4,8,0,19000.0,2017,"3269 Blinker Parkway, DuBois, PA 15801",60216.0,4,Champagne Frost Pearl,2.4L I4 16V GDI DOHC,Champagne Frost Pearl 2017 Honda Accord EX-L w...,https://www.cars.com/vehicledetail/a2020bcf-55...

# Part 2:  Exploratory Data Analysis
At a minimum, the EDA should include looking at some summary statistics, recognizing any issues with the data or key insights, and visual inspection of important data columns. We expect at least 3 visualizations.

In [23]:
df_cars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 366 entries, 0 to 436
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Dealer or Individual?  366 non-null    Int64
 1   Price                  366 non-null    float64
 2   Year                   366 non-null    int32
 3   Location               273 non-null    object
 4   Mileage                366 non-null    float64
 5   Doors                  366 non-null    int32
 6   Color                  364 non-null    object
 7   Engine                 366 non-null    object
 8   Description            354 non-null    object
 9   Web Link               366 non-null    object
dtypes: Int64(1), float64(2), int32(2), object(5)
memory usage: 29.0+ KB

In [24]:
dealer_individual_count = df_cars.groupby('Dealer or Individual?').size()
dealer_individual_count

Dealer or Individual?
0    332
1     30
2      4
dtype: int64

In [25]:
doors_count = df_cars.groupby('Doors').size()
doors_count

Doors
2     12
4    354
dtype: int64

In [26]:
years_count = df_cars.groupby('Year').size()
years_count

Year
2008    17
2009     6
2010    10
2011     6
2012    15
2013    18
2014    18
2015    15
2016    15
2017    23
2018    33
2019    16
2020    24
2021    14
2022    47
2023    18
2024    44
2025    27
dtype: int64

In [27]:
df_cars.describe()

,Dealer or Individual?,Price,Year,Mileage,Doors
count,366.0,366.000000,366.000000,366.000000,366.000000
mean,0.103825,19590.060109,2018.385246,70858.915301,3.934426
std,0.339438,8183.874377,4.940379,57011.464929,0.356644
min,0.0,0.000000,2008.000000,0.000000,2.000000
25%,0.0,12988.500000,2015.000000,19518.750000,4.000000
50%,0.0,20228.000000,2019.000000,65393.000000,4.000000
75%,0.0,25972.000000,2022.000000,107729.000000,4.000000
max,2.0,40450.000000,2025.000000,344597.000000,4.000000

In [49]:
alt.Chart(df_cars, title="Distribution of Car VS Years").mark_bar().encode(
    alt.X("Year:O").title("Years"),
    alt.Y("count()").title("Number of Cars")
).configure_axisX(
    labelAngle=45
)

alt.Chart(...)

In [54]:
alt.Chart(df_cars, title="Distribution of Cars VS Mileage").mark_bar().encode(
    alt.X("Mileage:O", bin=alt.Bin(maxbins=30)).title("Mileage Range"),
    alt.Y("count()").title("Number of Cars")
).configure_axisX(
    labelAngle=45
)

alt.Chart(...)

In [46]:
alt.Chart(df_cars, title= "Price VS Year").mark_circle().encode(
    alt.X("Year", scale=alt.Scale(domain=[2008, 2025])).title("Year"),
    alt.Y("Price").title("Price")
)

alt.Chart(...)

In [43]:
alt.Chart(df_cars, title="Price vs Mileage").mark_circle().encode(
    alt.X("Mileage").title("Mileage"),
    alt.Y("Price").title("Price")
)

alt.Chart(...)

Some insights:

1. Most car owners sell their manuals through dealers;
2. Most of the used cars for sale are four-door;
3. The price of second-hand cars generally shows a positive correlation with the year of sale. Theoretically, the closer the year is to the present, the less the car has been used, and the higher the selling price;
4. The price of used cars is generally negatively correlated with mileage. The higher the mileage, the lower the selling price of the car.

# Part 3: Question

Pose a question that you believe can be answered from the data. This should be in a clearly identified section in the same notebook.

Among the cars for sale, which mileage ranges have the highest number of cars?

# Part 4: Reflection

Insert here a reflection of your process. Did you feel you did the most efficient process to clean the dataset? Would your process be repeatable if you got a new dataset regularly with additional listings, or would it require much manual effort with each effort? Do you feel you adequately explored the dataset?   Do you feel your question is a good data science question (e.g. answerable, interesting, and at the right granularity).  

This section will not influence your grade on the above sections, so please feel free to be honest.

I think I did the most efficient process to clean the dataset. I think that the the frame of my process can be repeatable for most datasets,but there is no data cleaning process that can be applied to all datasets, we usually need to do extra manual effort to observe the raw dataset and think out the unique details of process for this dataset accordingly. I don't think that I adequately explored the dataset, because I did not consider the "description" column, which is time-consuming to extract keywords. I think my question is a good data science question.